### ISSUE TITLE
Отобразить предупреждения о пропусках студента в личном кабинете

### ISSUE THREAD

**Issue by mamutova** [esdpteam2java11/a-2_automation_system#320]
В личном кабинете спортсмена реализовать логику по предупреждению о непосещаемости студента последних трех занятий. Можно реализовать в виде alert или в виде информационного сообщения на странице.

Мотивация: реализация предупреждения согласно тз.
Критерии приемки: если авторизованный спортсмен не посещал последние три занятия, то должно выводиться сообщение.
Ожидаемое время выполнения: 2 часа.

**Comment by kasdan** [comment]
потратил 3 часа
